class Error(Exception):
    pass


class RangeError(Error):
    pass
